### ISSUE TITLE
SSL憑證錯誤

### ISSUE THREAD

**Issue by Yuan573** [arthurc0102/ntub-bot#1]
![憑證資訊](https://i.imgur.com/Fvr5UJS.png)
這個[機器人](https://ntub-bot.arthurc.me)的憑證有點問題 OAQ
可以參考看看[SSL for Free](https://www.sslforfree.com/)，目前也可以直接申請Wildcard SSL

**Comment by arthurc0102** [comment]
感謝提醒，其實我是使用 Let's Encrypt 簽署我的憑證的
不過前幾天測試其他系統的時候因為簽署的太頻繁以至於被鎖才會這樣 XD
目前還在等待限制解除 QAQ
